Y||(Y={});Y.Template||(Y.Template={});
Y.Template.noYUI={init:function(){this.setIndexFullscreenGalleryHeights();this.scrollYPolyfill();this.vCenterTopSectionContent()},scrollYPolyfill:function(){window.scrollY||(window.scrollY=window.pageYOffset||document.documentElement.scrollTop,window.addEventListener("scroll",function(){window.scrollY=window.pageYOffset||document.documentElement.scrollTop}))},setIndexFullscreenGalleryHeights:function(){if(document.querySelectorAll&&!(-1<document.body.className.indexOf(" design-grid"))){var a=document.querySelectorAll("body.collection-type-index.slideshow-aspect-ratio-fullscreen .gallery-wrapper");
if(0!==a.length)for(var b=window.innerHeight,c=0;c<a.length;c++)a[c].style.height=b+"px"}},vCenterTopSectionContent:function(){var a=window.getComputedStyle(document.getElementById("header"),null).getPropertyValue("position"),b=document.querySelector(".main-content .index-section:first-child");if(b){var c=0<b.querySelectorAll(".has-main-image").length,d=0<b.querySelectorAll(".index-gallery").length;if("absolute"==a&&c&&!d){var e=document.querySelector("#header .header-inner"),g=header.querySelector(".title-logo-wrapper"),
f=document.querySelector("#mainNavigation"),h=parseInt(window.getComputedStyle(e,null).paddingTop,10);if(f){f.style.whiteSpace="nowrap";f.style.display="inline";var k=f.offsetWidth+(2*g.offsetWidth-18);f.style.whiteSpace="normal";f.style.display="block";var i=0,j=g.offsetHeight,i=e.offsetWidth<k?(j+h)/2+f.offsetHeight:(j+h)/2;b.querySelector(".content-inner").style.paddingTop=i+"px";nIntervId=setInterval(function(){!1===(j===g.offsetHeight)&&(i=e.offsetWidth<k?(g.offsetHeight+h)/2+f.offsetHeight:
(g.offsetHeight+h)/2,b.querySelector(".content-inner").style.paddingTop=i+"px",clearInterval(nIntervId))},10);setTimeout(function(){clearInterval(nIntervId)},1E3)}}}}};Y.Template.noYUI.init();
(function(){var a=document.head||document.getElementsByTagName("head")[0],b=document.createElement("style"),c=document.body,d;b.type="text/css";b.styleSheet?b.styleSheet.cssText=".disable-hover:not(.sqs-layout-editing) #siteWrapper, .disable-hover:not(.sqs-layout-editing) #siteWrapper * {pointer-events: none !important;}":b.appendChild(document.createTextNode(".disable-hover:not(.sqs-layout-editing) #siteWrapper, .disable-hover:not(.sqs-layout-editing) #siteWrapper * {pointer-events: none !important;}"));
a.appendChild(b);window.addEventListener("scroll",function(){clearTimeout(d);c.classList.contains("disable-hover")||c.classList.add("disable-hover");d=setTimeout(function(){c.classList.remove("disable-hover")},200)},!1)})();
Y.namespace("Template").Lazyload=Class.create({initialize:function(a){this.el=a.el;this.mobile=a.mobile||!1;this.loadEvent=a.loadEvent||"throttle";"string"==typeof this.loadEvent&&(this.loadEvent=this.loadEvent.toLowerCase());if(!this.el)return console.error("lazyload.js: You must define an element."),!1;if(!1===this.mobile&&Y.UA.mobile)return Y.all(this.el).each(function(a){ImageLoader.load(a,{load:!0})}),!1;this.bindUI()},bindUI:function(){Y.all('img[data-load\x3d"viewport"]').each(function(a){ImageLoader.load(a)});
this.loadImages();this.mitigate="debounce"==this.loadEvent?function(){this.timeout&&this.timeout.cancel();this.timeout=Y.later(100,this,this.loadImages)}:Y.throttle(this.loadImages,200,this);Y.one(window).on("scroll",this.mitigate,this)},loadImages:function(){Y.all(this.el).each(function(a){a.getY()<1.5*Y.config.win.innerHeight+Y.config.win.scrollY&&ImageLoader.load(a,{load:!0})})},refresh:function(){this.loadImages()}});
Y.namespace("Template").RevealOnScroll=Class.create({initialize:function(a){this.el=a.el;this.offsetEl=a.offsetEl;this.behavior=a.behavior||"top";"string"==typeof this.behavior&&(this.behavior=this.behavior.toLowerCase());if(!this.el)return console.error("sticky.js: You must specify an element."),!1;if(!Y.one(this.el))return!1;this.bindUI()},bindUI:function(){this.getVariables();Y.one(window).on("resize",function(){this.getVariables();this.showOrHide()},this);this.throttle=Y.throttle(Y.bind(function(){this.showOrHide()},
this),200);this.debounce=function(){this.timeout&&this.timeout.cancel();this.timeout=Y.later(100,this,this.showOrHide)};Y.one(window).on("scroll",function(){this.throttle();this.debounce()},this);Y.one(window).on("hashchange",this.debounce,this);this.showOrHide()},getVariables:function(){Y.one(this.offsetEl)&&(this.y="bottom"==this.behavior?Y.one(this.offsetEl).getY()+Y.one(this.offsetEl).get("clientHeight")-Y.one(this.el).get("clientHeight"):Y.one(this.offsetEl).getY()-Y.one(this.el).get("clientHeight"))},
showOrHide:function(){Y.config.win.scrollY>=this.y?Y.one(this.el).addClass("show"):Y.one(this.el).removeClass("show")}});
Y.namespace("Template").CenterNav=Class.create({initialize:function(a){this.navItems=a.navItems;this.centerEl=a.centerEl;this.wrapper=a.wrapper;this.innerWrapper=a.innerWrapper;if(this.navItems)if(this.centerEl)if(this.wrapper){if(!this.innerWrapper)return console.error("centernav.js: You must specify an inner nav wrapper."),!1}else return console.error("centernav.js: You must specify an outer wrapper that contains the nav items and nav wrapper."),!1;else return console.error("centernav.js: You must specify an element to center around."),
!1;else return console.error("centernav.js: You must specify the nav items selector."),!1;this.bindUI()},bindUI:function(){if(1<Y.all(this.navItems).size())if(this.CENTER_SPACING=30,this.getVariables(),this.navSpace=(this.wrapperWidth-this.centerElWidth)/2,Y.one(".custom-cart")&&(this.navSpace=(this.wrapperWidth-this.centerElWidth)/2-(Y.one(".custom-cart").get("offsetWidth")+parseInt(Y.Squarespace.Template.getTweakValue("headerPadding"),10))),this.navItemsSplitPoint=Math.round(Y.all(this.navItems).size()/
2),this.splitPointWidth=Y.all(this.navItems).item(this.navItemsSplitPoint-1).get("offsetWidth"),this.navItemsLeft=Y.all(this.navItems).slice(0,this.navItemsSplitPoint),this.navItemsRight=Y.all(this.navItems).slice(this.navItemsSplitPoint),0!==Y.all(this.navItems).size()%2&&this.navItemsLeft.get("offsetWidth").reduce(this.sum,0)-this.splitPointWidth>this.navItemsRight.get("offsetWidth").reduce(this.sum,0)&&(this.navItemsSplitPoint-=1,this.navItemsLeft=Y.all(this.navItems).slice(0,this.navItemsSplitPoint),
this.navItemsRight=Y.all(this.navItems).slice(this.navItemsSplitPoint)),this.calculateWidthDiff(),this.leftOfLogo=Y.all(this.navItems).item(this.navItemsSplitPoint-1),this.rightOfLogo=Y.all(this.navItems).item(this.navItemsSplitPoint),this.navItemsLeft.get("offsetWidth").reduce(this.sum,0)>this.navSpace-12||this.navItemsRight.get("offsetWidth").reduce(this.sum,0)>this.navSpace-12)this.destroy(),Y.one(this.innerWrapper).setStyles({marginLeft:0,marginTop:"10px",marginBottom:0});else{this.destroy();
Y.one(this.leftOfLogo).setStyle("marginRight",this.centerElWidth/2);Y.one(this.rightOfLogo).setStyle("marginLeft",this.centerElWidth/2);var a=parseInt(Y.one(this.innerWrapper).getComputedStyle("height"),10);Y.one(this.innerWrapper).setStyles({marginLeft:this.widthDiff,marginTop:Math.ceil(-1*(this.centerElHeight/2+a/2)),marginBottom:Math.ceil(this.centerElHeight/2+a/2-a)})}Y.one(this.innerWrapper).addClass("positioned")},destroy:function(){Y.all(this.navItems).removeAttribute("style")},getVariables:function(){this.wrapperWidth=
Y.one(this.wrapper).get("offsetWidth")-2*parseInt(Y.Squarespace.Template.getTweakValue("headerPadding"),10);this.centerElWidth=Y.one(this.centerEl).get("offsetWidth")+2*this.CENTER_SPACING;this.centerElHeight=Y.one(this.centerEl).get("offsetHeight")},calculateWidthDiff:function(){this.widthDiff=this.navItemsRight.get("offsetWidth").reduce(this.sum,0)-this.navItemsLeft.get("offsetWidth").reduce(this.sum,0)},sum:function(a,b){if("number"==typeof a&&"number"==typeof b)return a+b;console.warn("centernav.js sum function: can't add non-numbers.");
return!1}});
Y.namespace("Template").Gallery=Class.create({initialize:function(a){this.slides=a.slides;this.wrapper=a.wrapper;if(!this.slides)return console.error("index-gallery.js: You have to define the slides selector."),!1;if(!this.wrapper)return console.error("index-gallery.js: You have to define the wrapper selector."),!1;if(!Y.one(this.wrapper)||!Y.one(this.slides))return!1;this.getTweaks();this.bindUI();this.syncUI()},bindUI:function(){if("grid"==this.tweak.design)this.loadGridImages(),this.lightboxSet=[],
Y.one(this.wrapper).all(this.slides).each(function(a){var b=a.one(".sqs-video-wrapper"),e=b?a.one(".sqs-video-wrapper"):a.one("img"),b=b?null:a.one(".slide-meta-content")&&a.one(".slide-meta-content").getHTML();this.lightboxSet.push({content:e,meta:b});a.on("click",function(b){b.halt();a.one(".clickthrough-link")?(b.stopPropagation(),window.location=a.one(".clickthrough-link").getAttribute("href")):(this.gallery&&this.gallery.destroy(),this.gallery=new Y.Squarespace.Lightbox2({controls:{previous:!0,
next:!0},currentSetIndex:Y.one(this.wrapper).all(this.slides).indexOf(a),set:this.lightboxSet}),this.gallery.render())},this)},this);else{var a=!1;"auto"==this.tweak.aspect&&(a=!0);var b=!1;!0===this.tweak.autoplay&&(b=!0);"fullscreen"==this.tweak.aspect&&"slideshow"==this.tweak.design&&this.fullscreen();this.wrapper.generateID();this.nodeID="#"+this.wrapper.get("id");this.galleryManager=[];this.gallery=new Y.Squarespace.Gallery2({container:this.wrapper,design:"stacked",autoplay:b,designOptions:{autoHeight:a,
clickBehavior:"auto",transition:this.tweak.transition},elements:{controls:this.nodeID+" ~ .circles",next:this.nodeID+" ~ .next-slide",previous:this.nodeID+" ~ .previous-slide"},historyHash:!1,keyboard:!1,lazyLoad:!0,loaderOptions:{mode:"fill"},loop:"true",refreshOnResize:!0,slides:this.slides});Y.one(this.wrapper).delegate("click",function(a){a.halt();a.currentTarget.ancestor(this.slides).toggleClass("hide-meta")},".hide-meta-toggle");this.galleryManager.push(this.gallery);this.keyboardControls()}},
syncUI:function(){Y.Template.helper.on("resizeend",function(){"grid"==this.tweak.design&&this.loadGridImages();"fullscreen"==this.tweak.aspect&&"slideshow"==this.tweak.design&&this.fullscreen()},this);Y.Global.on("tweak:reset",this.refresh,this);Y.Global.on("tweak:change",function(a){a=a.getName();("grid-aspect-ratio"==a||"slideshow-aspect-ratio"==a||"design"==a||"gallery-controls"==a||"slideshow-transition"==a||"slideshow-autoplay"==a)&&this.refresh();("grid-aspect-ratio"==a||"slideshow-aspect-ratio"==
a||"design"==a||"grid-max-columns"==a)&&Y.one(window).simulate("resize")},this)},getTweaks:function(){this.tweak={aspect:this.getTweakValue("slideshow-aspect-ratio"),design:this.getTweakValue("design"),nav:this.getTweakValue("gallery-controls"),transition:this.getTweakValue("slideshow-transition"),autoplay:this.getTweakValue("slideshow-autoplay")}},getTweakValue:function(a){a=Y.Squarespace.Template.getTweakValue(a);Y.Lang.isString(a)&&(a=a.toLowerCase());"true"===a?a=!0:"false"===a&&(a=!1);return a},
keyboardControls:function(){Y.one(window).on("keyup",function(a){Y.all(this.wrapper).each(function(b,c){if(b.inViewportRegion()&&(37==a.keyCode||39==a.keyCode)){var d=1;37==a.keyCode&&(d=-1);this.galleryManager[c].set("currentIndex",this.galleryManager[c].get("currentIndex")+d)}},this)},this)},fullscreen:function(){this.mobileNavShowing="none"==Y.one("#header .mobile-nav-toggle-label").getComputedStyle("display")?!1:!0;Y.all(this.wrapper).each(function(a){this.mobileNavShowing?a.setStyle("height",
Y.config.win.innerHeight):Y.one("#siteWrapper #content .index-section.gallery:first-child")&&Y.one("#showOnScrollWrapper #mainNavWrapper")?(a.setStyle("height",Y.config.win.innerHeight-Y.one("#showOnScrollWrapper #mainNavWrapper").get("clientHeight")),Y.one("#siteWrapper #content .index-section.gallery:first-child .gallery-wrapper").setStyle("height",Y.config.win.innerHeight)):Y.one("#showOnScrollWrapper #mainNavWrapper")?a.setStyle("height",Y.config.win.innerHeight-Y.one("#showOnScrollWrapper #mainNavWrapper").get("clientHeight")):
a.setStyle("height",Y.config.win.innerHeight)},this)},loadGridImages:function(){Y.one(this.wrapper).all(this.slides).each(function(a){a.one(".sqs-video-wrapper")?a.one(".sqs-video-wrapper").plug(Y.Squarespace.VideoLoader,{mode:"fill"}):ImageLoader.load(a.one("img"),{load:!0,mode:"fill"})},this)},destroy:function(){Y.all(this.wrapper).each(function(a){a.detachAll();a.removeAttribute("style")},this);Y.all(this.slides).each(function(a){a.detachAll();a.removeAttribute("style")},this);this.gallery&&this.gallery.destroy()},
refresh:function(){this.destroy();this.getTweaks();this.bindUI()}});
Y.use("node",function(a){a.namespace("Template").Site=Singleton.create({ready:function(){this.regularHeaderForGridGallery();a.on("domready",function(){this.init()},this)},init:function(){this.cartState();this._touch=a.one(".touch-styles");a.one(".index-section .index-section-image")&&this.fadeInFirstIndexSectionImageOnLoad();this.transparentHeaderPadding();this.textShrink("#siteTitle a","#siteTitle");this.textShrink(".index-gallery .slide-meta-content .title",".index-gallery .slide-meta-content");
this.textShrink(".index-section-wrapper.has-main-image .sqs-block-content h1",".index-section-wrapper.has-main-image .sqs-block-content");this.textShrink(".banner-thumbnail-wrapper .desc-wrapper h1",".banner-thumbnail-wrapper .desc-wrapper");this.textShrink(".quote-block figure",".sqs-block.quote-block");this.textShrink(".page-description p",".page-description");this.getVariables();this.wrapper=a.Node.create('\x3cdiv class\x3d"show-on-scroll-wrapper" id\x3d"showOnScrollWrapper"\x3e\x3c/div\x3e');
this.injectScrollNavContent();this.syncUI();this.bindUI();this._touch||a.one(".always-use-overlay-nav")||768>=a.config.win.innerWidth?(a.Template.helper.radioCheckboxes("#mainNavigation"),a.Template.helper.radioCheckboxes("#mobileNavigation")):(a.Template.helper.folderRedirect("#headerNav .folder-toggle-label"),a.Template.helper.folderRedirect("#footer .folder-toggle-label"))},fadeInFirstIndexSectionImageOnLoad:function(){a.one(".index-section-image img").on("load",function(a){a.currentTarget.addClass("loaded")})},
mutationObserver:function(b,c,d){var e=window.MutationObserver||window.WebKitMutationObserver||window.MozMutationObserver;if(e){var g=new e(d);g.observe(b,c);var f=a.later(15E3,this,function(){g.disconnect();f.cancel()})}else d(null,null)},bindUI:function(){this.mutationObserver(a.one("#siteWrapper").getDOMNode(),{childList:!0,subtree:!0},this.mutationCallback);a.one(window).on("resize",function(){this.getVariables();this.syncUI();a.Template.noYUI.vCenterTopSectionContent()},this);a.Squarespace.Singletons.ShoppingCart.on("change",
a.Template.Site.cartState);this.disableScroll();a.Template.helper.on("resizeend",function(){a.all(".map-block[data-block-json]").each(function(b){a.Template.helper.centerMapPin(b.one(".page-map"),JSON.parse(b.getData("block-json")))})});a.one(".collection-type-index")&&(a.all(".index-gallery").each(function(b){new a.Template.Gallery({wrapper:b.one(".gallery-wrapper"),slides:".slide-wrapper"})}),a.one(".collection-type-index.homepage")&&new a.Template.RevealOnScroll({el:"#showOnScrollWrapper",offsetEl:".index-section-wrapper",
behavior:"bottom"}));a.one(".index-section-image img")&&2<=a.all(".index-section-image img").length?this.lazyload?this.lazyload.refresh():this.lazyload=new a.Template.Lazyload({el:".index-section-image img",mobile:!1,loadEvent:"throttle"}):a.all(".index-section-image img").each(function(a){ImageLoader.load(a.removeAttribute("data-load"))});this.scrollNav();this.altSections(a.all(".index-section.no-main-image"));a.Template.helper.scrollAnchors()},syncUI:function(){this.runCenterNav();this.overlayNavPadding();
this.folderEdgeDetection();a.Template.helper.on("resizeend",this.scrollNav,this);a.Template.helper.on("resizeend",this.injectScrollNavContent(),this);a.one(".collection-type-index.homepage")?(this.scrollNavHeight=a.one("#showOnScrollWrapper #mainNavWrapper")?a.one("#showOnScrollWrapper #mainNavWrapper").get("clientHeight"):0,a.all(this.navLinks).each(function(b){b.on("click",function(c){window.location.hash&&history.pushState("",document.title,window.location.pathname);c.halt();c=b.getAttribute("href");
var d;"/"===c.charAt(0)&&(c=c.substr(1));a.one(c)&&(d=this.mobileNav?a.one(c).getY()+1:a.one(c).getY()-this.scrollNavHeight+1,this.mobileNav?(a.one("#mobileNavToggle").set("checked",!1).simulate("change"),a.later(400,this,function(){a.Template.helper.smoothScrollTo(d)})):a.Template.helper.smoothScrollTo(d))},this)},this)):this.mobileNav&&a.all(this.navLinks).each(function(b){b.on("click",function(){a.one("#mobileNavToggle").set("checked",!1).simulate("change")},this)},this)},mutationCallback:function(b){if(b)for(var c=
0;c<b.length;c++){if(b[c].addedNodes.length)for(var d=0;d<b[c].addedNodes.length;d++){var e=a.Node(b[c].addedNodes[d]);e.ancestor(".index-section-wrapper.has-main-image")&&ImageLoader.load(e.ancestor(".index-section-wrapper").one(".index-section-image img"));window.location.hash&&(e=window.location.hash,"/"===e.charAt(0)&&(e=e.substr(1)),a.one(e)&&a.one(window).set("scrollTop",a.one(e).getY()+1))}}else a.on("io:end",function(){var b=a.later(1200,this,function(){a.all(".index-section-image img").each(function(a){ImageLoader.load(a)});
b.cancel()})})},getVariables:function(){this.headerHeight=a.one("#header").get("offsetHeight");this.mobileNav=this._touch||a.one(".always-use-overlay-nav")||768>=a.config.win.innerWidth;this.navLinks=".nav-wrapper .index.home a";this.mobileNavShowing="none"==a.one("#header .mobile-nav-toggle-label").getComputedStyle("display")?!1:!0},scrollNav:function(){if(a.one(".collection-type-index.homepage")&&a.one("#header #mainNavWrapper")&&a.one(".index.home")){var b=a.all(".index-section:not(.gallery)"),
c=this.mobileNavShowing?a.all("#mobileNavWrapper .index.home"):a.all("#showOnScrollWrapper #mainNavigation .index.home"),d=0,e=0,g=this.mobileNavShowing?0:a.one("#showOnScrollWrapper #mainNavWrapper").get("clientHeight")+1,f=a.throttle(a.bind(function(){b.each(function(b,c){c=c++;b.getY()<a.config.win.scrollY+g&&(d=c)},this);a.config.win.scrollY+a.config.win.innerHeight>=a.one("body").get("clientHeight")?(c.item(c.size()-1).addClass("active"),d=c.size()-1):c.item(d).addClass("active");d!=e&&(c.item(e).removeClass("active"),
e=d)},this),200);a.one(window).on("scroll",f);a.Template.helper.on("scrollend",f)}},cartState:function(){var b=a.Squarespace.Singletons.ShoppingCart.get("totalQuantity"),c=a.one(".custom-cart");c&&(b&&0<b?c.removeClass("empty"):c.hasClass("empty")||c.addClass("empty"))},disableScroll:function(){var b=a.one("#mobileNavToggle");b.on("change",function(){!0===b.get("checked")?a.one("body").addClass("disable-scroll"):a.one("body").removeClass("disable-scroll")});a.Template.helper.disableScroll("disable-scroll")},
textShrink:function(b,c){a.one(b)&&a.one(b).ancestor(c)&&a.all(b).each(function(b){b.plug(a.Squarespace.TextShrink,{parentEl:b.ancestor(c)})})},regularHeaderForGridGallery:function(){a.one(".collection-type-index.design-grid.has-banner-image")&&a.one("#page #content .index-section:first-child .index-section-wrapper .gallery-content")?a.one("body").removeClass("has-banner-image"):a.one(".collection-type-index.design-slideshow:not(.has-banner-image)")&&a.one("#page #content .index-section:first-child .index-section-wrapper .gallery-content")&&
a.one("body").addClass("has-banner-image")},fadeIn:function(b){a.one(b)&&a.one(b).hasClass("tmpl-loading")&&a.all(b).each(function(a){a.removeClass("tmpl-loading").addClass("tmpl-loaded")})},runCenterNav:function(){if(a.one("body:not(.always-use-overlay-nav)")){var b="#header #mainNavigation \x3e div";a.one(".index.home")&&(b="#header #mainNavigation \x3e div:not(.home)",a.one(".expand-homepage-index-links")&&(b="#header #mainNavigation \x3e div:not(.base)"));new a.Template.CenterNav({navItems:b,
centerEl:"#header .title-logo-wrapper h1",wrapper:"#header",innerWrapper:"#header #headerNav"})}},overlayNavPadding:function(){640<a.config.win.innerWidth&&a.one("#overlayNav #mainNavWrapper")&&a.one("#overlayNav #mobileNavWrapper").setStyles({paddingTop:this.headerHeight,paddingBottom:this.headerHeight})},folderEdgeDetection:function(){a.all(".subnav").each(function(b){a.config.win.innerWidth-b.getX()<=b.get("offsetWidth")&&b.addClass("right-align")})},transparentHeaderPadding:function(){var b=a.one("#header").getComputedStyle("position"),
c=(a.one("#header .header-inner h1").get("offsetHeight")+parseInt(a.one("#header .header-inner").getComputedStyle("paddingTop"),10))/2;"absolute"==b&&a.one(".main-content .index-section:first-child .index-section-wrapper.has-main-image")||("absolute"==b&&a.one("body.has-banner-image")?(a.one(".banner-thumbnail-wrapper .desc-wrapper")&&a.one(".banner-thumbnail-wrapper .desc-wrapper").setStyle("paddingTop",c),a.all('.banner-thumbnail-wrapper img[data-load\x3d"false"]').each(function(a){ImageLoader.load(a.removeAttribute("data-load"))})):
a.all('.banner-thumbnail-wrapper img[data-load\x3d"false"]').each(function(a){ImageLoader.load(a.removeAttribute("data-load"))}))},injectScrollNavContent:function(){a.one(".collection-type-index.homepage")&&a.one("#header #mainNavWrapper")&&(a.one("#showOnScrollWrapper")&&a.one("#showOnScrollWrapper").empty(),this.fixedEl=this.mobileNav?".show-on-scroll-mobile":".show-on-scroll",a.one("#mobileNavToggle").insert(this.wrapper.setHTML(a.one(this.fixedEl).get("outerHTML")),"after"),".show-on-scroll"==
this.fixedEl&&a.all("#showOnScrollWrapper #mainNavWrapper nav div").removeAttribute("style"))},altSections:function(a){a.each(function(a){a.get("nextElementSibling")&&a.get("nextElementSibling").hasClass("index-section.no-main-image")&&!a.hasClass("alt-section")&&a.get("nextElementSibling").addClass("alt-section")})}})});
Y.use("node","event-custom",function(){Y.namespace("Template").helper=Singleton.create({ready:function(){Y.on("domready",function(){this.bindUI()},this);Y.augment(this,Y.EventTarget,!0,null,{emitFacade:!0})},bindUI:function(){this.dataToggleBody();this.dataToggleEl();this.dataLightbox();Y.one(window).on("resize",function(){this._resize&&this._resize.cancel();this._resize=Y.later(150,this,function(){this.fire("resizeend")});this.syncUI()},this);Y.one(window).on("scroll",function(){this._scroll&&this._scroll.cancel();
this._scroll=Y.later(150,this,function(){this.fire("scrollend")})},this)},syncUI:function(){if(Y.one(".touch-styles"))Y.one(window).on("orientationchange",function(){this.imgLoad()},this);else Y.Template.helper.on("resizeend",function(){this.imgLoad()})},radioCheckboxes:function(a,b,c){a?Y.one(a)?(b=b||'[type\x3d"checkbox"]',c=c||"label[for]",1<Y.one(a).all(b).size()&&Y.one(a).delegate("click",function(c){c.preventDefault();c=Y.one("#"+c.currentTarget.getAttribute("for"));!1===c.get("checked")?(Y.one(a).all(b).each(function(a){a.set("checked",
!1)}),c.set("checked",!0)):c.set("checked",!1)},c)):console.warn("radioCheckboxes: No wrapper found on page."):console.warn("radioCheckboxes: Must define a wrapper.")},folderRedirect:function(a,b){a=a||"label[for]";b=b||"body";Y.one(a)&&Y.one(b).delegate("click",function(a){a.preventDefault();(a=a.currentTarget.getData("href"))?window.location=a:console.warn("folderRedirect: You must add a data-href attribute to the label.")},a)},dataLightbox:function(){var a={};Y.all("[data-lightbox]").each(function(b){var c=
b.getAttribute("data-lightbox");a[c]=a[c]||[];a[c].push({content:b,meta:b.getAttribute("alt")});b.on("click",function(d){d.halt();(new Y.Squarespace.Lightbox2({set:a[c],currentSetIndex:Y.all("[data-lightbox]").indexOf(b),controls:{previous:!0,next:!0}})).render()})})},dataToggleBody:function(){Y.one("body").delegate("click",function(a){Y.one("body").toggleClass(a.currentTarget.getData("toggle-body"))},"[data-toggle-body]")},dataToggleEl:function(){Y.one("body").delegate("click",function(a){a=a.currentTarget;
a.toggleClass(a.getData("toggle"))},"[data-toggle]")},debounce:function(a,b,c){b=b||100;c=c||Y.Template.Site;a&&(this._timeout&&this._timeout.cancel(),this._timeout=Y.later(b,c,a))},imgLoad:function(a){Y.all(a||"img[data-src]").each(function(a){ImageLoader.load(a)})},scrollAnchors:function(a){if(!history.pushState)return!1;if(a){if("string"!=typeof a)return console.warn("helpers.js: scrollAnchors argument must be a string."),!1;Y.all(a).each(function(a){if(a.hasAttribute("href"))"#"==!a.getAttribute("href").substring(0,
1)&&console.warn("helpers.js: scrollAnchors links must start with a hash.");else return console.warn("helpers.js: scrollAnchors must have href attributes."),!1})}Y.one("body").delegate("click",function(a){a.halt();a=a.target.getAttribute("href");Y.one(a)&&this.smoothScrollTo(Y.one(a).getY());history.pushState({},a,a)},a||'a[href^\x3d"#"]',this)},smoothScrollTo:function(a){if(NaN==parseInt(a))return console.warn("helpers.js: smoothScrollTo must have a scroll point passed to it."),!1;if(!Y.Lang.isNumber(a))try{a=
parseInt(a)}catch(b){return console.warn("helpers.js: scrollTo was passed an invalid argument."),!1}if(Y.UA.mobile)window.scroll(0,a);else{var c=new Y.Anim({node:Y.one(Y.UA.gecko||Y.UA.ie||navigator.userAgent.match(/Trident.*rv.11\./)?"html":"body"),to:{scrollTop:a},duration:0.4,easing:"easeOut"});c.run();c.on("end",function(){c.destroy()})}},disableScroll:function(a){if(!Y.Lang.isString(a))return console.warn("helpers.js: disableScroll arg must be a string."),!1;var b=Y.config.win.scrollY;Y.one(window).on("scroll",
function(){Y.one("body").hasClass(a)?window.scrollTo(0,b):b=Y.config.win.scrollY},this)},centerMapPin:function(a,b){var c=a._node.__map;if(!c)return console.error("helpers.js: Invalid argument passed to centerMapPin method."),!1;var d=c.getCenter();d.d=b.location.mapLat;d.e=b.location.mapLng;google.maps.event.trigger(c,"resize");c.setCenter(d)}})});
Y.use("node",function(a){a.namespace("Template").Authenticated=Singleton.create({ready:function(){this.bindUI()},bindUI:function(){a.Global.on("tweak:beforeopen",function(){setTimeout(function(){a.one(window).simulate("resize")},500)});a.Global.on(["tweak:save","tweak:discard","tweak:beforeopen"],function(){a.one(".always-use-overlay-nav")&&a.one("#mobileNavToggle").set("checked",!1).simulate("change")});a.Global.on("tweak:discard",function(){});a.Global.on("tweak:close",function(){setTimeout(function(){a.one(window).simulate("resize")},
500);a.one("#header.tweaking")&&a.one("#header.tweaking").removeClass("tweaking")});a.Global.on("tweak:aftershow",function(){a.Template.noYUI.vCenterTopSectionContent();a.Template.Site.runCenterNav()},this);a.Global.on("tweak:change",function(b){var c=b.getName();b=b.getValue();"string"==typeof b&&(b=b.toLowerCase(),b=b.replace(" ","-"));if("siteTitleContainerWidth"==c||"logoWidth"==c)a.one("#header").addClass("tweaking"),a.Template.helper.debounce(function(){a.one("#header").removeClass("tweaking")},
500);"design"==c&&a.Template.Site.regularHeaderForGridGallery();a.one(".always-use-overlay-nav")&&("nav-font"==c||"navColor"==c||"navActiveColor"==c||"expand-homepage-index-links"==c)&&a.one("#mobileNavToggle").set("checked",!0).simulate("change");"always-use-overlay-nav"==c&&(a.Template.Site.injectScrollNavContent(),a.Template.noYUI.vCenterTopSectionContent(),a.Template.Site.runCenterNav());("siteTitleContainerWidth"==c||"logoWidth"==c||"nav-font"==c||"expand-homepage-index-links"==c)&&a.later(140,
this,function(){a.Template.noYUI.vCenterTopSectionContent();a.Template.Site.runCenterNav()});"transparent-header"==c&&a.Template.helper.debounce(function(){a.Template.helper.imgLoad()})})}})});